name: CI
on:
  push:
    branches:
     - test_actions
     - main
jobs:
  build-llvmta:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tu-dortmund-ds-ls12-daes-teaching/llvmta-devcontainer
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
       - name: Checkout (GitHub)
         uses: actions/checkout@v2
       - name: Build
         run: ./config.sh rel ; cd build ; ninja llvmta
