name: CI
on:
  push:
    branches:
     - test_actions
     - main
jobs:
  build-llvmta:
    runs-on: ubuntu-latest
      container:
        image: ghcr.io/nilhoel1/llvmta-devcontainer
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      steps:
        - uses: actions/checkout@v2
        - run: ninja --version ; ls
