name: CI

on:
  push:
    branches:
      - test_actions
      - main

jobs:
  wait-for-container:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Container to be build
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: "Build and run dev container task"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  build-llvmta:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tu-dortmund-cs-ls12-daes-teaching/llvmta-devcontainer
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: .ccache
          key: ${ { matrix.config.name } }-ccache-${ { steps.ccache_cache_timestamp.outputs.timestamp } }
          restore-keys: |
            ${ { matrix.config.name } }-ccache-

      - name: Build
        run: ./config.sh rel ; cd build ; ninja llvmta
